"""empty message

Revision ID: 05feaeb1cdc6
Revises: 1de0d0aa19eb
Create Date: 2023-07-10 01:18:06.413402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05feaeb1cdc6'
down_revision = '1de0d0aa19eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_claims',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name='user_claims_fk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_claims_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'claim_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_claims')
    op.drop_table('roles')
    op.drop_table('claims')
    # ### end Alembic commands ###
