version: "3"

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=shipay
      - POSTGRES_PASSWORD=shipay
      - POSTGRES_DB=shipayDB
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # application:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - database
