version: "3"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=shipay
      - POSTGRES_PASSWORD=shipay
      - POSTGRES_DB=shipayDB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
